### ISSUE TITLE
ModuleNotFoundError: No module named 'core'

### ISSUE THREAD

**Issue by Pasechneek** [ads-txt/validator#6]
[2022-08-18 13:38:12 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2022-08-18 13:38:12 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2022-08-18 13:38:12 +0000] [1] [INFO] Using worker: sync
[2022-08-18 13:38:12 +0000] [9] [INFO] Booting worker with pid: 9
[2022-08-18 13:38:12 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'core'
[2022-08-18 13:38:12 +0000] [9] [INFO] Worker exiting (pid: 9)
[2022-08-18 13:38:12 +0000] [1] [INFO] Shutting down: Master
[2022-08-18 13:38:12 +0000] [1] [INFO] Reason: Worker failed to boot.

**Comment by Pasechneek** [comment]
Fixed via adding this: 
django-cors-headers = "3.11.0"     
build-backend = "poetry.core.masonry.api"        into **pyproject.toml**

then:

gunicorn
core-lib
psycopg2
django-core==1.4.1
environ                                                        into **requirments.txt**

but, something is excess and I will delete that

**Comment by Pasechneek** [comment]
This also helpful:
https://docs.gunicorn.org/en/latest/run.html
(if you use guincorn)
Becouse guincorn also has core.
